---
UI Settings:
  Sidebar Side: "RIGHT"
  Sidebar Opacity: 0.7
  Sidebar Width: 200.0
General Settings:
  Map Service ID: "osm"
  Map Service Category: "Global"
Hologram Settings:
  Y Align: 0.0
  Lock North: true
  Projection JSON: ""
  X Align: -0.06666666666667226
  Opacity: 1.0
  Do Render: false
  Y Diff Limit: 1000.0
  Z Align: 4.6463529041116305E-17
  Flat Map Y Axis: 4.0
